# Use Node.js 20 (LTS)
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies inside the container
RUN npm install --force

# Copy the rest of the app
COPY . .

# Expose the backend port
EXPOSE 5000

# Start the backend server
CMD ["node", "server.js"]
